#-----------------------------------------------------------
# Bacula-fd (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-fd
  name: bacula-fd
  namespace: bacula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-fd
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula-fd
    spec:
      containers:
      - image: docker.io/eftechcombr/bacula:15.0.2-client
        name: bacula-fd
        ports:
        - containerPort: 9102
        volumeMounts:
        - name: bacula-fd
          mountPath: "/opt/bacula/etc"
          readOnly: true
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: bacula-fd
        configMap:
          name: bacula-fd


---
#-----------------------------------------------------------
# Modo de publicacion de Bacula-fd
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-fd
  name: bacula-fd
  namespace: bacula
spec:
  type: ClusterIP
  selector:
    app: bacula-fd
  ports:
  - port: 9102
    protocol: TCP
    targetPort: 9102
