#---------------------------------------------------------------------
# Archivo de configuracion bacularis-web (API Host)
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: bacularis-api
  namespace: bacula
data:
  api.conf: |-
    [api]
    auth_type = "basic"
    debug = "0"
    lang = "en"

    [db]
    enabled = "1"
    type = "pgsql"
    name = "bacula"
    login = "bacula"
    password = "bacula"
    ip_addr = "postgresql-node-rw"
    port = "5432"
    path = ""

    [bconsole]
    enabled = "1"
    bin_path = "/usr/sbin/bconsole"
    cfg_path = "/etc/bacula/bconsole.conf"
    use_sudo = "1"

    [jsontools]
    enabled = "1"
    use_sudo = "1"
    bconfig_dir = "/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config"
    bdirjson_path = "/usr/sbin/bdirjson"
    dir_cfg_path = "/etc/bacula/bacula-dir.conf"
    bsdjson_path = "/usr/sbin/bsdjson"
    sd_cfg_path = "/etc/bacula/bacula-sd.conf"
    bfdjson_path = "/usr/sbin/bfdjson"
    fd_cfg_path = "/etc/bacula/bacula-fd.conf"
    bbconsjson_path = "/usr/sbin/bbconsjson"
    bcons_cfg_path = "/etc/bacula/bconsole.conf"

    [actions]
    enabled = "1"
    use_sudo = "1"
    dir_start = "/etc/bacula/scripts/bacula-ctl-dir start"
    dir_stop = "/etc/bacula/scripts/bacula-ctl-dir stop"
    dir_restart = "/etc/bacula/scripts/bacula-ctl-dir restart"
    sd_start = "/etc/bacula/scripts/bacula-ctl-sd start"
    sd_stop = "/etc/bacula/scripts/bacula-ctl-sd stop"
    sd_restart = "/etc/bacula/scripts/bacula-ctl-sd restart"
    fd_start = "/etc/bacula/scripts/bacula-ctl-fd start"
    fd_stop = "/etc/bacula/scripts/bacula-ctl-fd stop"
    fd_restart = "/etc/bacula/scripts/bacula-ctl-fd restart"

  bacularis.users: |-
    admin:$apr1$6hYFTlhE$0vj91PWcNlEjodBYuCEr9/

  basic.conf: |-
    [admin]
    bconsole_cfg_path = ""

---
#---------------------------------------------------------------------
# ConfigMap para corregir entrypoint de Bacula
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: bacula-entrypoint-fix
  namespace: bacula
data:
  docker-entrypoint.sh: |-
    #!/usr/bin/env bash
    
    set -e
    
    # Cargar funciones auxiliares y de parada, ignorando fallos de ejecución si los hay
    . /docker-entrypoint.inc || true

    # 1. Función para omitir la inicialización del catálogo interno
    function init_bacula() {
        echo "Saltando inicialización de catálogo. Usando catálogo externo."
    }

    # 2. Redefinir la función para iniciar el Director de Bacula
    # Esta función YA NO hace 'psql -l' porque eso está fallando sin el servidor interno.
    function start_bacula_dir()
    {
        echo "Iniciando Director de Bacula (conectado a DB externa)..."
        # Esto iniciará el servicio bacula-dir, el cual leerá el bacula-dir.conf
        # y se conectará a 'postgresql-node-rw.bacula-test.svc.cluster.local'
        /etc/bacula/scripts/bacula-ctl-dir start
    }
    
    # 3. Redefinir la función START para omitir la DB interna (start_postgresql)
    function start()
    {
        echo "PostgreSQL interno deshabilitado. Iniciando Director y API..."
        
        start_bacula_dir
        
        # 4. Iniciar PHP-FPM para Bacularis API
        php-fpm84
    }

    # 5. Ejecutar el inicio de servicios
    start
    
    # 6. Ejecutar el CMD original (nginx -g daemon off;)
    exec "$@"

---
#---------------------------------------------------------------------
# ServiceAccount para Bacula-dir
#---------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bacula-dir-sa
  namespace: bacula
  labels:
    app: bacula-dir
    component: director

---
#-----------------------------------------------------------
# PersistentVolumeClaim para Bacula-dir
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bacula-dir-data
  namespace: bacula
spec:
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
#-----------------------------------------------------------
# Bacula-dir (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: bacula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-dir
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula-dir
    spec:
      serviceAccountName: bacula-dir-sa
      terminationGracePeriodSeconds: 60
      # -----------------------------------------------------------
      # INIT CONTAINER: Sincronización + Permisos de Ejecución (+x)
      # -----------------------------------------------------------
      initContainers:
      - name: init-bacula-config
        image: bacularis/bacularis-api-dir:5.8.0-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "=== Iniciando reparación de permisos Bacula ==="
            # 1. Asegurar directorios
            mkdir -p /mnt/config/scripts
            # 2. Copiar scripts (Sobrescribir para reparar corruptos)
            echo "Copiando scripts desde la imagen..."
            cp -Rfv /etc/bacula/scripts/* /mnt/config/scripts/
            # 3. Copiar configuración base si falta
            if [ ! -f "/mnt/config/bacula-dir.conf" ]; then
               echo "Inicializando configuración base..."
               find /etc/bacula -maxdepth 1 -type f -exec cp {} /mnt/config/ \;
               cp -rn /etc/bacula/conf.d /mnt/config/ || true
            fi
            # 4. FIX CRÍTICO: ASIGNAR PROPIETARIO Y PERMISOS DE EJECUCIÓN
            echo "Aplicando permisos..."
            # A. El dueño debe ser bacula (UID suele ser 1000 o 33 en estas imagenes)
            chown -R bacula:bacula /mnt/config
            # B. Dar permisos totales (775) a todo para evitar 'Permission denied'
            # Esto asegura que los scripts tengan el bit (+x) activado
            chmod -R 775 /mnt/config
            echo "=== Reparación completada. Listo para arrancar. ==="
        volumeMounts:
          - name: bacula-dir-data
            mountPath: /mnt/config
      containers:
      - image: bacularis/bacularis-api-dir:5.8.0-alpine
        name: bacula-dir
        ports:
        - containerPort: 9097
        - containerPort: 9101
        env:
        - name: TZ
          value: "America/Lima"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        # Volumenes de bacula-dir
        - name: bacula-dir-data
          mountPath: /etc/bacula/
        # Volumenes de bacularis-api
        - name: bacularis-api
          mountPath: /var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config/api.conf
          subPath: api.conf
        - name: bacularis-api
          mountPath: /var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs/bacularis.users
          subPath: bacularis.users
        - name: bacularis-api
          mountPath: /var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working/basic.conf
          subPath: basic.conf
        # Volumen de corrección de entrypoint
        - name: entrypoint-fix
          mountPath: /docker-entrypoint.sh
          subPath: docker-entrypoint.sh
          readOnly: true
      volumes:
      # Volumenes de bacula-dir 
      - name: bacula-dir-data
        persistentVolumeClaim:
          claimName: bacula-dir-data
      # Volumenes de bacularis-api
      - name: bacularis-api
        configMap:
          name: bacularis-api
      # Volumen de corrección de entrypoint
      - name: entrypoint-fix
        configMap:
          name: bacula-entrypoint-fix
          defaultMode: 0755

---
#-----------------------------------------------------------
# Modo de publicacion de Bacula-Director
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: bacula
spec:
  type: LoadBalancer
  selector:
    app: bacula-dir
  ports:
  - port: 9097
    protocol: TCP
    targetPort: 9097
    name: api-port
  - port: 9101
    protocol: TCP
    targetPort: 9101
    name: dir-port

---
#-----------------------------------------------------------
# PodDisruptionBudget to keep at least one replica available
#-----------------------------------------------------------
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bacula-dir-pdb
  namespace: bacula
  labels:
    app: bacula-dir
    component: director
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bacula-dir