apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: bacula
type: Opaque
data:
  ACCESS_KEY_ID: c2E3cEdwV1c5cEVHTVVQNFNMOWk=
  ACCESS_SECRET_KEY: RlRDNGtpVWowQnhScUVzRkFEcllQenZGYW0zZ3JRTk83OWZFRnZjYQ==