apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: bacula
type: kubernetes.io/basic-auth
data:
  username: YmFjdWxh # base64 encoded value for 'bacula'
  password: YmFjdWxh # base64 encoded value for 'bacula'
