#---------------------------------------------------------------------
# Archivo de configuracion baculum-web
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: baculum-web
  namespace: bacula
data:
  baculum.users: |-
    admin:YWG41BPzVAkN6

  hosts.conf: |-
    [Main]
    auth_type = "basic"
    login = "admin"
    password = "admin"
    client_id = ""
    client_secret = ""
    redirect_uri = ""
    scope = ""
    protocol = "http"
    address = "baculum-api"
    port = "9096"
    url_prefix = ""

  settings.conf: |-
    [baculum]
    debug = "0"
    lang = "en"
    max_jobs = "15000"
    size_values_unit = "decimal"
    time_in_job_log = "0"
    date_time_format = "Y-M-D R"
    enable_messages_log = "1"
    login = "admin"

    [users]

    [auth_basic]
    allow_manage_users = "1"
    user_file = "/etc/baculum/Config-web-apache/baculum.users"
    hash_alg = "apr-md5"

    [security]
    auth_method = "basic"
    def_access = "default_settings"
    def_role = "normal"
    def_api_host = "Main"

  users.conf: |-
    [admin]
    long_name = ""
    description = ""
    email = ""
    roles = "admin"
    api_hosts = ""
    enabled = "1"
    ips = ""

---
#-----------------------------------------------------------
# Baculum (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baculum-web
  name: baculum-web
  namespace: bacula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baculum-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: baculum-web
    spec:
      initContainers:
      - image: docker.io/eftechcombr/baculum:11.0.6-web
        name: baculum-init
        volumeMounts:
        - name: baculum-web
          mountPath: "/tmp/baculum/Config-web-apache"
          readOnly: true
        - name: etc-baculum-web
          mountPath: "/etc/baculum"
        command:
          - bash
          - -c
          - "cp -Rf /tmp/baculum/Config-web-apache /etc/baculum && chmod a+w /etc/baculum/Config-web-apache"
      containers:
      - image: docker.io/eftechcombr/baculum:15.0.2-web
        name: baculum-web
        command:
        - "/usr/sbin/apache2ctl"
        args:
        - "-D"
        - "FOREGROUND"
        ports:
        - containerPort: 9095
        volumeMounts:
        - name: etc-baculum-web
          mountPath: "/etc/baculum"
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi" 
      volumes:
      - name: baculum-web
        configMap:
          name: baculum-web
      - name: etc-baculum-web
        emptyDir: {}          

---
#-----------------------------------------------------------
# Modo de publicacion de Baculum
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baculum-web
  name: baculum-web
  namespace: bacula
spec:
  type: LoadBalancer
  selector:
    app: baculum-web
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 9095
