#---------------------------------------------------------------------
# Archivo de configuracion baculum-api
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: baculum-api
  namespace: bacula
data:
  baculum.users: |-
    admin:YWG41BPzVAkN6

  api.conf: |-
    [api]
    auth_type = "basic"
    debug = "0"
    lang = "en"

    [db]
    enabled = "1"
    type = "pgsql"
    name = "bacula"
    login = "bacula"
    password = "bacula"
    ip_addr = "postgresql-node-rw.bacula.svc.cluster.local"
    port = "5432"
    path = ""

    [bconsole]
    enabled = "1"
    bin_path = "/opt/bacula/bin/bconsole"
    cfg_path = "/opt/bacula/etc/bconsole.conf"
    use_sudo = "0"

    [jsontools]
    enabled = "1"
    use_sudo = "0"
    bconfig_dir = "/etc/baculum/"
    bdirjson_path = "/opt/bacula/bin/bdirjson"
    dir_cfg_path = "/opt/bacula/etc/bacula-dir.conf"
    bsdjson_path = "/opt/bacula/bin/bsdjson"
    sd_cfg_path = "/opt/bacula/etc/bacula-sd.conf"
    bfdjson_path = "/opt/bacula/bin/bfdjson"
    fd_cfg_path = "/opt/bacula/etc/bacula-fd.conf"
    bbconsjson_path = "/opt/bacula/bin/bbconsjson"
    bcons_cfg_path = "/opt/bacula/etc/bconsole.conf"

---

#-----------------------------------------------------------
# Baculum-API (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baculum-api
  name: baculum-api
  namespace: bacula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baculum-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: baculum-api
    spec:
      initContainers:
      - image: docker.io/eftechcombr/baculum:11.0.6-api
        name: baculum-init
        volumeMounts:
        - name: baculum-api
          mountPath: "/tmp/baculum/Config-api-apache"
          readOnly: true
        - name: etc-baculum-api
          mountPath: "/etc/baculum"
        command:
          - bash
          - -c
          - "cp -Rf /tmp/baculum/Config-api-apache /etc/baculum && chmod a+w /etc/baculum/Config-api-apache"
      containers:
      - image: docker.io/eftechcombr/baculum:15.0.2-api
        name: baculum-api
        command:
        - "/usr/sbin/apache2ctl"
        args:
        - "-D"
        - "FOREGROUND"
        ports:
        - containerPort: 9096
        volumeMounts:
        - name: etc-baculum-api
          mountPath: "/etc/baculum"
        - name: bconsole
          mountPath: "/opt/bacula/etc/bconsole.conf"
          subPath: bconsole.conf
          readOnly: true 
        - name: bacula-dir
          mountPath: "/opt/bacula/etc/bacula-dir.conf"
          subPath: bacula-dir.conf
          readOnly: true 
        - name: bacula-fd
          mountPath: "/opt/bacula/etc/bacula-fd.conf"
          subPath: bacula-fd.conf 
          readOnly: true
        - name: bacula-sd
          mountPath: "/opt/bacula/etc/bacula-sd.conf"
          subPath: bacula-sd.conf 
          readOnly: true
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: bacula-sd
        configMap:
          name: bacula-sd
      - name: bacula-dir
        configMap:
          name: bacula-dir
      - name: bacula-fd
        configMap:
          name: bacula-fd
      - name: baculum-api
        configMap:
          name: baculum-api
      - name: bconsole
        configMap: 
          name: bconsole
      - name: etc-baculum-api
        emptyDir: {}

---
#-----------------------------------------------------------
# Modo de publicacion de Baculum-API
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baculum-api
  name: baculum-api
  namespace: bacula
spec:
  type: ClusterIP
  selector:
    app: baculum-api
  ports:
  - port: 9096
    protocol: TCP
    targetPort: 9096
